version: '3.7'

services:
  backend:
    build : ./
    container_name: matelo-mantra-backend
    volumes:
      - static:/static
    env_file:
      - .env
    ports:
      - 5001:8000
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - backend

  #      PROXY_API: http://playground-web-backend:8080/
  frontend:
    build: ./frontend/
    container_name: matelo-mantra-frontend
    ports:
      - 5002:8080

volumes:
  static: