version: '3'

services:

  backend:
    build : ./
    container_name: matelo-mantra-backend-1
    ports:
      - 5001:8000
#      PROXY_API: http://playground-web-backend:8080/
    volumes:
      - ./mounts/db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
  frontend:
    build: ./frontend/
    container_name: matelo-mantra-frontend
    ports:
      - 5002:8080
